fix: change ftp server to file server
IBM/Ansible-OpenShift-Provisioning pull request #102
Opened 2023-02-22 05:26 UTC by jacobemery

Related to Issue #96 

The name 'FTP server' is confusing since the KVM host is now capable of hosting and serving necessary files via http only. Update the docs and variables to represent this change. 

Also, enable using either ftp or http to serve config files for the bastion. FTP is still the only option for booting the KVM hosts, and HTTP will still be installed and used on the bastion as it is required. But with these changes, someone using a pre-existing KVM host can use only HTTP. And someone using an FTP server for booting of the KVM host can use that same FTP server to boot the bastion.

2023-02-22 05:28 UTC, jacobemery commented
Received feedback from users that this was confusing to them, decided to tackle it today. Tested a highly-available deployment (3 LPARs, macvtap) with env.file_server.protocol as 'ftp' and entire test run as 'http'.

2023-02-22 06:01 UTC, smolin-de requested changes
This statement:
"KVM host is now capable of hosting and serving necessary files via http"
is WRONG !
A guest on a KVM host does not have a network connection to the 
host via macvtap !

2023-02-22 09:44 UTC, smolin-de commented on docs/set-variables-group-vars.md
> +**env.file_server.iso_mount_dir** | Directory path relative to the HTTP/FTP accessible directory where RHEL ISO is mounted. For example, if the FTP root is at /home/user1<br /> and the ISO is mounted
**env.file_server.iso_mount_dir** | Directory path relative to the HTTP/FTP accessible directory where RHEL ISO is mounted. For example, if the FTP root is at /home/user1<br /> and the ISO is mounted at /home/user1/RHEL/8.7 then this variable would be<br /> RHEL/8.7 - no slash before or after. | RHEL/8.7

2023-02-22 19:31 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**env.file_server.iso_mount_dir** | Directory path relative to the HTTP/FTP accessible directory where RHEL ISO is mounted. For example, if the FTP root is at /home/user1<br /> and the ISO is mounted
Done

2023-02-23 03:02 UTC, jacobemery commented
> A guest on a KVM host does not have a network connection to the KVM host via macvtap !
Ah, you are correct, my apologies! I've updated the description. Looks like none of the code has to change, but that was a lapse in my understanding, thanks!

Everything else look ok @smolin-de ?

2023-02-23 04:59 UTC, smolin-de approved these changes
ok

2023-02-23 06:57 UTC, merged

2023-08-18 14:52 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: