feat: add optional setup_file_server.yaml playbook
IBM/Ansible-OpenShift-Provisioning pull request #105
Opened 2023-02-23 07:27 UTC by jacobemery

Add a playbook to setup the file server as "executable documentation". The file server's setup causes a lot of confusion for users. This is not part of the official install path, but meant to be a helpful additional resource if needed.

Also adds accompanying documentation in prerequisites and run_the_playbooks pages.

2023-03-07 20:53 UTC, jacobemery commented
@smolin-de what do you think?

2023-04-10 04:04 UTC, jacobemery commented
Ah thanks for the comment @smolin-de. I didn't see it until now because it looks like you edited my comment with your response. I didn't even know that could be done! 

I think it's helpful for up setting up new environments, and as a form of "executable documentation" where all the setup required is laid out plainly, and can be run if needed.

Does anything need to be modified in your opinion, or do you have any other thoughts? Still needs your official review.

2023-09-15 14:51 UTC, AmadeusPodvratnik commented
@jacobemery I went through the changes and have some comments:
- It's not clear where to install the FTP server. Basically a FTP server can be installed on KVM but than macvtap is not working. Using NAT, nodes have access to the KVM host. Make it sense to mention it. 
- Make it sense to have a simple index page user can query (e.g. curl command). E.g.:
<html>
<head/>
<body>Installation of FTP Server was successful!/body>
</html>
- Why you removed the mount commands from documentation? I feel they are helpful and worth to be mentioned.

2023-10-10 11:33 UTC, AmadeusPodvratnik requested changes
Thx @jacobemery for the PR. I tested it and have following comments:
- due to the fact that a file_server entry in the hosts file is needed, this should be documented.
- Make it sense to automate this step in case an user would like to have it "all together". E.g. if a user would like to have it all self contained than this step can be integrated into a more general setup playbook. 
- For macvtap network mode any other VM can be used if the LPAR has access to. Is this something you would like to mention?

2023-12-20 23:11 UTC, jacobemery commented
Needs rebase.

2026-04-11 02:05 UTC, closed without merging