Changed to handle creation & configuration of Bastion for hypershift
IBM/Ansible-OpenShift-Provisioning pull request #147
Opened 2023-05-26 18:05 UTC by veera-damisetti

2023-05-30 08:20 UTC, veera-damisetti commented
As of now , we are not supporting NAT. We dit  it with Macvtap and another approach called Routed bridge is still in exploration. 
We need separate bastion for hypershift because one Management cluster can handle multiple Hosted Clusters , using management cluster bastion for all hcp is is not possible so , we are using separate bastion for each Hosted Cluster 

Reason for using separate playbook/role for hypershift bastion , 
the way the existing role creating a bastion is a bit different than our approach 
they are using some hash for bastion root password but i am doing it using the same vault which i am using for cluster credentials.
and  in our bastion we are adding localhost ssh key in bastion.ks  file for eliminating establishment of key-based authentication .

2023-05-30 10:11 UTC, AmadeusPodvratnik requested changes
@veera-damisetti You need to document the fact that NAT is not supported but only macvtap. This is a limitation and hypershift will not work for e.g. on IBM Cloud. In addition it's to mentioned that a separate node is needed and created called bastion and pls call it differently to the existing bastion. Within one documentation to talk about bastion might be irritating.
In addition you are using a separate kickstart file for your bastion which is different from the existing one. E.g. keyboard layout, timezone, baseurl etc. All those parameters users should be able to configure. The installation should work outside of our environment, too (e.g. customer like Dataport). Pls check existing kickstart file and use it as template or use the existing kickstart file.
There should be the kernel fix available (pls check current version on prod) so you can download the kernel.img out of the ipxe script (no need for the ISO workaround). I verified this on staging.

2023-06-01 09:43 UTC, irmsan commented
if that is a target, should be implemented as a "optional" playbook

2023-06-01 09:48 UTC, veera-damisetti commented
You are talking about create_bastion_hypershift  role ..?

2023-06-01 09:49 UTC, irmsan commented
i am talking about all the new functions what creates a "huuuuuge" dinosaur from this

2023-06-01 09:50 UTC, veera-damisetti commented
So you mean to  make entire hypershift installation playbooks optional ..?

2023-06-01 09:53 UTC, AmadeusPodvratnik commented
Hypershift is an optional step because it's a day-2 operation.

2023-06-01 09:53 UTC, irmsan commented
I think, that any new function that is not a "main" stream should be optional (like hypershift, like add remove nodes, etc...)

2023-06-01 09:56 UTC, irmsan commented
I don't agree 100%, while hypershift can be day-1 (someone wants to install that as default, and not later fight with that)

If I understood correctly hypershift is where masters are sitting on x86, thinking they are on "Z"

2023-06-01 09:56 UTC, AmadeusPodvratnik commented
@irmsan But this is the case .. if you install a cluster fresh there is no need to install hypershift ... But if you want to, you can.

2023-06-01 09:58 UTC, AmadeusPodvratnik commented
@irmsan And there is a need to support multiarch which means that you will be able to run hypershift wherever you want.

2023-06-14 09:52 UTC, AmadeusPodvratnik requested changes
Hi @veera-damisetti, I believe we need a change here:
- name: Create xml for macvtap
  copy:
    content: | 
      <network>
        <name>macvtap-net</name>
        <forward mode="bridge">
          <interface dev="enc1100"/>
        </forward>
      </network>
    dest: /root/ansible_workdir/macvtap-def.xml
  when: not network_exists

- name: Create macvtap network if it doesn't exists
  shell: | 
    virsh net-define /root/ansible_workdir/macvtap-def.xml
    virsh net-autostart macvtap-net
    virsh net-start macvtap-net
  when: not network_exists
  
Due to the fact that hypershift supports macvtap only and a mixture between NAT and macvtap will not happen  (install OCP using NAT and proceed with macvtap for hypershift).
I believe that you tested hypershift with macvtap only, right?
So in case of a macvtap only installation I would suggest to use the existing macvtap network defenition you find in /roles/macvtap/ .
This means that you don't need to handle the macvtap and use env.bridge_name to create the bastion instead.
If you tested a NAT OCP install and have macvtap in parallel for hypershift, than you should parameterize the macvtap settings just in case there is already a macvtap network setting which should be used. As an example you can check the macvtap settings from regular OCP installation like env.bridge_name or networking.device1, etc. You should not hardcode enc1100 as interface because you don't know if it will exist.

2023-06-15 15:58 UTC, jacobemery requested changes
Hi Veera, a ton of great work here!

The most important feedback I have here is to use the Ansible modules for tasks whenever possible. Using the 'shell' module should be the last resort, as it is not idempotent and will throw errors very easily. 

Great job adding documentation as a part of the PR, much appreciated there!

2023-06-15 15:58 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +# Task 0
No need for commenting the number of tasks, please remove
```suggestion
```

2023-06-15 15:58 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +# Task 1
```suggestion
```

2023-06-15 15:58 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +  shell: mkdir -p /home/libvirt/images/
```suggestion
- name: Create Directory for images and bastion.ks
  file: 
    path: /home/libvirt/images/
    recurse: true
    state: directory
```
Please use Ansible modules wherever possible, shell module is not idempotent.

This is untested ^

2023-06-15 15:58 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +    src: ../create_bastion/templates/bastion-ks.cfg.j2
```suggestion
    src: bastion-ks.cfg.j2
```
if this template is in the templates folder of the role, all you should need is the filename

2023-06-15 15:58 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +        line: "rootpw {{bastion_root_pw}}"
```suggestion
- name: Adding root password for bastion to bastion.ks
  lineinfile:
    path: /home/libvirt/bastion.ks
    insertafter: '^lang.*'
    line: "rootpw {{bastion_root_pw}}"
```

2023-06-15 15:58 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +          chmod 0600 /root/.ssh/authorized_keys
These should all be individual tasks that use ansible modules, it is currently not idempotent

2023-06-15 15:58 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +  command: virt-install --name {{ hypershift.hcp.hosted_cluster_name }}-bastion --memory 4096 --vcpus sockets=1,cores=4,threads=1 --disk /home/libvirt/images/{{ hypershift.hcp.hosted_cluster_name }}-
Please see other virt-install tasks, such as create_bastion/tasks/main.yaml, for formatting this task to be more readable.

Basically it needs to be spliced up with a \ at the end of each line.

2023-06-15 15:58 UTC, jacobemery commented on roles/download_rootfs_hypershift/tasks/main.yaml
> +  yum:
```suggestion
  package:
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  loop: "{{ env.pkgs.bastion }}"
```suggestion
- name: Install Packages on bastion
  package:
    name: "{{ env.pkgs.bastion }}"
    state: present
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  loop: "{{ env.pkgs.bastion }}"
Use generalized package module.

Something I found out recently is that the package module is sped up significantly by putting the list of packages in the 'name' parameter instead of looping the list.

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  command: tar -C /usr/local -xzf /root/ansible_workdir/go{{ hypershift.go_version }}.linux-s390x.tar.gz
Please use the 'unarchive' module for idempotency

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  command: chmod 755 /usr/local/bin/go
Please use the 'file' module

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  shell: source ~/.bash_profile
This will not add variables from the bash_profile to be usable in Ansible. Each individual task is a new shell session. If you'd like to use variables that are set there, they have to be defined as Ansible variables.
```suggestion
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  when: hypershift_check.rc != 0
These should be separate Ansible tasks that use their respective modules.

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +    content: "{{hypershift.hcp.pull_secret}}"
```suggestion
    content: "{{ hypershift.hcp.pull_secret }}"
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +    dest: /root/ansible_workdir/auth_file
Root is required? Could it be a user with sudo access?

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  register: mgmt_workers
```suggestion
- name: Get the number of Management Cluster Worker Nodes 
  shell: oc get no -o wide --no-headers|grep -i worker| awk '{print $6}' | wc -l
  register: mgmt_workers_count
  changed_when: false

- name: Get the IPs of Management Cluster Workers 
  shell: oc get no -o wide --no-headers|grep -i worker| awk '{print $6}' 
  register: mgmt_workers
  changed_when: false
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  register: mgmt_workers
add changed_when: false to avoid incorrect labeling of the task

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/templates/haproxy.cfg.j2
> +frontend {{hypershift.hcp.hosted_cluster_name}}-api-server
```suggestion
frontend {{ hypershift.hcp.hosted_cluster_name }}-api-server
```

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prerequisites_host_hypershift/tasks/main.yaml
> +  shell: pip install kubernetes --ignore-installed PyYAML
Why the change to shell instead of using the pip module?

2023-06-15 15:58 UTC, jacobemery commented on roles/install_prerequisites_host_hypershift/tasks/main.yaml
>    yum:
```suggestion
  package:
```

2023-06-15 15:58 UTC, jacobemery commented on roles/setup_for_agents_hypershift/tasks/main.yaml
> +  shell: mkdir -p /var/lib/libvirt/images/pxeboot/
Please use Ansible 'file' module

2023-06-15 15:58 UTC, jacobemery commented on roles/setup_for_agents_hypershift/tasks/main.yaml
> +  shell: curl -k -L -o /var/lib/libvirt/images/pxeboot/initrd.img "{{ initrd_url }}"
Please use 'get_url' module

2023-06-15 15:58 UTC, jacobemery commented on roles/setup_for_agents_hypershift/tasks/main.yaml
> +  shell: curl -k -L -o /var/lib/libvirt/images/pxeboot/kernel.img "{{ kernel_url }}"
Please use 'get_url' module

2023-06-15 15:58 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +# Task 1
I didn't mark all of them

2023-06-16 03:03 UTC, veera-damisetti commented on playbooks/create_hosted_cluster.yaml
> +# Task 0
Done

2023-06-16 03:20 UTC, veera-damisetti commented on roles/create_bastion_hypershift/tasks/main.yaml
> +  command: virt-install --name {{ hypershift.hcp.hosted_cluster_name }}-bastion --memory 4096 --vcpus sockets=1,cores=4,threads=1 --disk /home/libvirt/images/{{ hypershift.hcp.hosted_cluster_name }}-
done

2023-06-16 03:34 UTC, veera-damisetti commented on roles/install_prerequisites_host_hypershift/tasks/main.yaml
> +  shell: pip install kubernetes --ignore-installed PyYAML
changed to use pip module

2023-06-16 03:35 UTC, veera-damisetti commented on roles/create_bastion_hypershift/tasks/main.yaml
> +    src: ../create_bastion/templates/bastion-ks.cfg.j2
this template is not there in  'templates' folder of the role , i am using the template that other  existing role is using

2023-06-16 03:46 UTC, veera-damisetti commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  command: tar -C /usr/local -xzf /root/ansible_workdir/go{{ hypershift.go_version }}.linux-s390x.tar.gz
done

2023-06-16 04:00 UTC, veera-damisetti commented on roles/setup_for_agents_hypershift/tasks/main.yaml
> +  shell: curl -k -L -o /var/lib/libvirt/images/pxeboot/kernel.img "{{ kernel_url }}"
done

2023-06-16 04:00 UTC, veera-damisetti commented on roles/setup_for_agents_hypershift/tasks/main.yaml
> +  shell: mkdir -p /var/lib/libvirt/images/pxeboot/
done

2023-06-16 04:47 UTC, veera-damisetti commented on roles/create_bastion_hypershift/tasks/main.yaml
> +          chmod 0600 /root/.ssh/authorized_keys
here i am not executing these commands , i am adding these block of lines to bastion.ks file

2023-06-16 09:49 UTC, veera-damisetti commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +    dest: /root/ansible_workdir/auth_file
yes but , we are logging in to bastion as root user always. so giving like that .. 

Is it like , we need to give other users to login to bastion also .?

2023-06-29 09:11 UTC, AmadeusPodvratnik approved these changes
Hi @veera-damisetti, the code looks good to me. Maybe you might approve the documentation or bring in a picture how hypershift will look like. This would be a doc enhancement and help other users to understand it better.
The next imporvement you should think about is the combination of day one and day two operation. If an user is installing OCP and will just continue with hypershift only one bastion should be used and the existing hypervisor should be used too. This is an good enhancement for my point of view.

2023-06-29 09:12 UTC, AmadeusPodvratnik commented
@jacobemery Can you pls proceed with this PR pls. Thank you.

2023-07-04 16:06 UTC, veera-damisetti commented
@AmadeusPodvratnik thanks  for the review and documentation  i need to improve definitely once everything is done for hypershift. and regarding combination of day1 and day2 activities , even though if user opt for hypershift on day1, we might need to use another bastion because one OCP cluster ( management cluster ) can be used for multiple hosted clusters.

2023-07-04 16:10 UTC, veera-damisetti commented
Documentation changes i am doing along with other changes ( remaining part of hypershift ) , as the partial documentation already updated which is needed till the process whatever i did.
So i am planning the remaining documentation and remaining code changes in another PR. 
sounds good ..?

2023-07-06 18:23 UTC, jacobemery requested changes
Some small requested changes and suggestions. Very close to merging.

2023-07-06 18:23 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +  go_version: "1.20.3"  # Change this if you want to install any other version  of go
```suggestion
  go_version: "1.20.3"  # Change this if you want to install any other version of go
```

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
>  **hypershift.kvm_host** | IPv4 address of KVM host for hypershift <br /> ( kvm host where you want to run all oc commands and create VMs)| 192.168.10.1
```suggestion
**hypershift.kvm_host** | IPv4 address of KVM host for hypershift <br /> (kvm host where you want to run all oc commands and create VMs)| 192.168.10.1
```

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.create_bastion** | Mark it to 'true' if you want to create bastion with the provided IP (hypershift.bastion_hypershift) <br /> 'false' if bastion already there with that IP | 'true'
```suggestion
**hypershift.create_bastion** | True or False - create bastion with the provided IP (hypershift.bastion_hypershift) | True
```

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.bastion_parms.gate_way** | Gateway IP for creating bastion <br /> This is how it well be used ip=<ipv4 address>::<nameserver>:<subnet mask> | 192.168.10.1
```suggestion
**hypershift.bastion_parms.gateway** | Gateway IP for creating bastion <br /> This is how it well be used ip=<ipv4 address>::<nameserver>:<subnet mask> | 192.168.10.1
```
All other gateway variables don't have the underscore. Let's keep it consistent. References to this variable will also need to be changed.

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.bastion_parms.base_domain** | Basedomain for bastion | lnxero1.boe
```suggestion
**hypershift.bastion_parms.base_domain** | DNS base domain for the bastion. | ihost.com
```

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.bastion_parms.base_domain** | Basedomain for bastion | lnxero1.boe
Avoid using real examples.

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
>  **hypershift.hcp.BASEDOMAIN** | Base domain for Hosted Cluster | example.com
```suggestion
**hypershift.hcp.CLUSTERS_NAMESPACE** | Namespace for Creating Hosted Control Plane | clusters
**hypershift.hcp.HOSTED_CLUSTER_NAME** | Name for the Hosted Cluster  | hosted0
**hypershift.hcp.BASEDOMAIN** | Base domain for Hosted Cluster | example.com
```
Any reason why these and other variables are capitalized? If not, please lowercase them to remain consistent.

2023-07-06 18:23 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.asc.mce_namespace** | Namespace where your Multicluster Engine Operator is installed <br /> Recommended Namespace for MCE is 'multicluster-engine' <br /> Change this only if MCE is insta
```suggestion
**hypershift.asc.mce_namespace** | Namespace where your Multicluster Engine Operator is installed. <br /> Recommended Namespace for MCE is 'multicluster-engine'. <br /> Change this only if MCE is installed in other namespace. | multicluster-engine
```

2023-07-06 18:23 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
```suggestion
```

2023-07-06 18:23 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +
```suggestion
```

2023-07-06 18:23 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +
Remove all empty spaces

2023-07-06 18:23 UTC, jacobemery commented on playbooks/create_hosted_cluster.yaml
> +    - name: Configure Bastion
```suggestion
        host: 'bastion_hypershift'
        
    - name: Install Prereqs
      import_role:
        name: install_prerequisites_host_hypershift
        
    - name: Configure Bastion
```
Add single space between tasks

2023-07-06 18:23 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +  shell: ip route add {{ hypershift.bastion_hypershift }} via {{ hypershift.gateway}}
```suggestion
  command: "ip route add {{ hypershift.bastion_hypershift }} via {{ hypershift.gateway }}"
```

2023-07-06 18:23 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +#-----------------------------------------------------------
```suggestion
#-----------------------------------------------------------
# Installing Go
#-----------------------------------------------------------
```
Don't need comments to explain what is being done. Use 'name:' parameter.

2023-07-06 18:23 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  command: setsebool -P haproxy_connect_any on
```suggestion
- name: turn on haproxy_connect_any 
  ansible.posix.seboolean: 
    name: haproxy_connect_any
    persistent: true
    state: true
```
Use idempotent seboolean module: https://docs.ansible.com/ansible/latest/collections/ansible/posix/seboolean_module.html

2023-07-06 18:23 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/templates/haproxy.cfg.j2
> +backend {{hypershift.hcp.hosted_cluster_name}}-api-server
```suggestion
backend {{ hypershift.hcp.hosted_cluster_name }}-api-server
```

2023-07-06 18:23 UTC, jacobemery commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +  ansible.builtin.command:
```suggestion
  command:
```

2023-07-06 18:23 UTC, jacobemery commented on roles/download_rootfs_hypershift/tasks/main.yaml
> +  shell: curl -k -L -o /var/www/html/rootfs.img "{{ rootfs_url }}"
```suggestion
- name: Download rootfs image 
  shell: curl -k -L -o /var/www/html/rootfs.img "{{ rootfs_url }}"
```
Any reason this can't use the get_url module?

2023-07-06 18:23 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +    ssh_key: "{{encoded_ssh.content | b64decode |replace('\n','')}}"
```suggestion
    ssh_key: "{{ encoded_ssh.content | b64decode |replace('\n','') }}"
```

2023-07-06 18:23 UTC, jacobemery commented on roles/create_bastion_hypershift/tasks/main.yaml
> +    ssh_key: "{{encoded_ssh.content | b64decode |replace('\n','')}}"
Why is it base 64 encoded?

2023-07-07 04:07 UTC, veera-damisetti commented on docs/set-variables-group-vars.md
>  **hypershift.hcp.BASEDOMAIN** | Base domain for Hosted Cluster | example.com
Done

2023-07-07 04:16 UTC, veera-damisetti commented on roles/install_prereqs_bastion_hypershift/tasks/main.yaml
> +#-----------------------------------------------------------
Done

2023-07-07 04:22 UTC, veera-damisetti commented on roles/download_rootfs_hypershift/tasks/main.yaml
> +  shell: curl -k -L -o /var/www/html/rootfs.img "{{ rootfs_url }}"
Updated to use  get_url module

2023-07-07 05:49 UTC, veera-damisetti commented on roles/create_bastion_hypershift/tasks/main.yaml
> +    ssh_key: "{{encoded_ssh.content | b64decode |replace('\n','')}}"
Yeah i think it is not needed . I did it as i used slurp module for getting ssh key from remote host 

changes done and removed the decoding part

2023-07-07 05:50 UTC, veera-damisetti commented
@jacobemery Thanks for the requested changes 
i have done the changes and resolved al conversations.

2023-07-07 13:13 UTC, smolin-rh commented on docs/set-variables-group-vars.md
> +**hypershift.bastion_parms.os_variant** | rhel os variant for creating bastion | 8.4
```suggestion
**hypershift.bastion_parms.os_variant** | rhel os variant for creating bastion | 8.7
```

2023-07-07 17:51 UTC, jacobemery approved these changes
Nice work!! Looks great.

2023-07-07 17:52 UTC, merged

2023-08-18 14:50 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: