feat: Static IP support for agents using NMState - Hypershift
IBM/Ansible-OpenShift-Provisioning pull request #181
Opened 2023-07-21 17:20 UTC by veera-damisetti

Added  changes required for supporting Static IP configuration

- Adds labels to InfraEnv 
- Deploy NMStateConfig resources for Static IP configuration

Updated documentation for the same

2023-07-24 12:55 UTC, AmadeusPodvratnik reviewed
Hi @veera-damisetti, I believe that hypershift should support zVM, too. For zVM and nmstate you need mac adr., too. Later this might confuse the user and I would suggest to have an option generating mac addresses or specify them.

2023-07-24 14:46 UTC, veera-damisetti commented
@AmadeusPodvratnik  yes , hypershift should support zVM. but i think  this playbooks ( Ansible Openshift Provisioning ) is only for kvm. 
should we consider zvm also while writing playbooks ..?

2023-07-25 15:31 UTC, AmadeusPodvratnik commented
> @AmadeusPodvratnik yes , hypershift should support zVM. but i think this playbooks ( Ansible Openshift Provisioning ) is only for kvm. should we consider zvm also while writing playbooks ..? if yes , i am already generating the mac address in the code . cant we use like that for zvm could you please explain ? ( I am not familiar with zvm static IP configuration )

At the moment these playbooks are for KVM only but zVM will follow soon so pls keep this fact in mind. You can't generate MAC addresses for zVM but using those addresses provided by the support team. Static MAC addresses are only required if nmstate is being used or DHCP. So you have already a list the user can specify, so only a flag (generate mac addresses or use list is missing).

2023-07-25 16:25 UTC, pswilso2017 commented
> 

I would recommend leaving this project KVM focused and we can work on either a fork or a separate project for z/VM.  Just my two cents.

2023-07-25 16:33 UTC, veera-damisetti commented
@AmadeusPodvratnik Added  **generate_mac_addr** flag  to allow user to give specific mac address to agents even in case of static IP . This might help even in case of KVM 
Thanks ..!

2023-07-26 19:33 UTC, jacobemery requested changes
Nice work, just a few suggestions. Let me know what you think

2023-07-26 19:33 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.agents_parms.static_ip_parms.generate_mac_addr** | true or false - set to false if you want to use a specific mac addresses for agents in case of static IP configuration | true
```suggestion
**hypershift.agents_parms.static_ip_parms.static_ip** | true or false - use static IPs for agents using NMState | true
**hypershift.agents_parms.static_ip_parms.ip** | List of IP addresses for agents | 192.168.10.1
**hypershift.agents_parms.static_ip_parms.interface** | Interface for agents for configuring NMStateConfig | eth0
**hypershift.agents_parms.static_ip_parms.generate_mac_addr** | true or false - randomly generate mac addresses for agents or manually specify them | true
```

2023-07-26 19:33 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**hypershift.agents_parms.agent_mac_addr** | Give here list of macaddresses for the agents <br /> These mac addresses should be configured in DHCP if you are using dynamic IPs for Agents | - 52:54:00
```suggestion
**hypershift.agents_parms.agent_mac_addr** | List of macaddresses for the agents. <br /> Configure in DHCP if you are using dynamic IPs for Agents. | - 52:54:00:ba:d3:f7 
```

2023-07-26 19:33 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +      generate_mac_addr: 'true'
```suggestion
    static_ip_parms:
      static_ip: true
      ip:     # Required only if static_ip is true
        #- 
        #- 
      interface: eth0
      generate_mac_addr: true
```

2023-07-26 19:33 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +    - #
```suggestion
    # Give the list of macaddress for agents here if you want to use specific mac addresses
    agent_mac_addr:  
      #- 
```
Instead of a variable defining whether mac addresses are manually specified by the user or randomly generated, it should be determined automatically based on whether the variable is defined or not. What do you think @veera-damisetti ?

Defined -> use that mac address
Undefined -> randomly generate one

2023-07-26 19:33 UTC, jacobemery commented on roles/boot_agents_hypershift/tasks/main.yaml
>      --name "{{ hypershift.hcp.hosted_cluster_name }}-agent-{{item}}" \
```suggestion
    --name "{{ hypershift.hcp.hosted_cluster_name }}-agent-{{ item }}" \
```

2023-07-26 19:33 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +      generate_mac_addr: 'true'
quotes around a boolean value turn it into a string

2023-07-26 19:33 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +    - #
Could be the same for whether or not static IPs are used too

2023-07-26 19:33 UTC, jacobemery commented on roles/create_hcp_InfraEnv_hypershift/tasks/main.yaml
> +    agent_mac_addr: "{{ agent_mac_addr +  ['52:54:00' | community.general.random_mac] }}"
I didn't know about 'community.general.random_mac', very cool!

2023-07-27 04:09 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +    - #
@jacobemery  this sounds good . Will update

2023-07-27 05:32 UTC, veera-damisetti commented on roles/create_hcp_InfraEnv_hypershift/tasks/main.yaml
> +    agent_mac_addr: "{{ agent_mac_addr +  ['52:54:00' | community.general.random_mac] }}"
Yeah i came to know this because of this scenario

2023-07-27 05:38 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +    - #
Updated. 
Thanks ...!

2023-07-27 07:18 UTC, veera-damisetti commented
Added installation of Multicluster engine operator

2023-07-28 17:01 UTC, jacobemery requested changes
A few nit-picks in inventory.

Any reason why you're using 'command' and 'shell' modules for a lot of the 'oc' commands instead of 'k8s' module? If it's possible, it would make the playbook more idempotent. Are you testing for idempotency?

I see you added MCE operator install. Ok by me, just requested one change with the mce delete variable name, that will require changes to its references as well. Let me know what you think. 

Almost there! Really great work Veera.

2023-07-28 17:27 UTC, veera-damisetti commented on roles/delete_resources_bastion_hypershift/tasks/main.yaml
> +  when: hypershift.mce.delete_mce_while_deleting_resources == true
No specific reason but  i can update these to use k8s module

2023-07-28 17:27 UTC, veera-damisetti commented on roles/delete_resources_bastion_hypershift/tasks/main.yaml
> +  when: hypershift.mce.delete_mce_while_deleting_resources == true
Updated

2023-07-28 17:33 UTC, jacobemery approved these changes

2023-07-28 17:34 UTC, merged

2023-08-18 14:50 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: