Fix for issue #188 (root user support)
IBM/Ansible-OpenShift-Provisioning pull request #197
Opened 2023-09-08 11:48 UTC by AmadeusPodvratnik

Fix for issue #188 (root user suport). In addition set 0 for ip_forward  var as default because macvtap is default network setting. In addition add var for subscription management.

2023-09-08 23:21 UTC, jacobemery requested changes
Since the decision to attach a subscription or not is a yes or no question, could you change env.redhat.manage_subscription to a boolean value? That way you don't have to normalize the case of the string, or reference the docs to see what the available options are. Also if it's just true of false, it's simpler to reference the variable in a playbook, you can just write "when: env.redhat.manage_subscription".

2023-09-08 23:28 UTC, jacobemery requested changes
Suggestions to go along with previous comments about changing manage_subscription to a boolean value. Let me know what you think!

2023-09-08 23:28 UTC, jacobemery commented on docs/set-variables-group-vars.md
> +**env.redhat.manage_subscription** | In case that the supscription of the OS should be attached. Possible values: no/attach | attach
```suggestion
**env.redhat.attach_subscription** | True or False. Would you like to subscribe the server with Red Hat? | True 
```

2023-09-08 23:28 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +    manage_subscription: attach
```suggestion
    attach_subscription: true
```

2023-09-08 23:28 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +    ip_forward: 0
```suggestion
    ip_forward: "{{ 1 if network_mode | upper == 'NAT' else 0 }}"
```
What do you think about changing to this?

2023-09-08 23:28 UTC, jacobemery commented on inventories/default/group_vars/all.yaml.template
> +    ip_forward: 0
One less variable to forget to change when using NAT.

2023-09-08 23:28 UTC, jacobemery commented on playbooks/3_setup_kvm_host.yaml
> +    - { role: attach_subscription, when:  env.redhat.manage_subscription | upper == 'ATTACH' }
```suggestion
    - { role: attach_subscription, when:  env.redhat.attach_subscription }
```

2023-09-11 07:57 UTC, AmadeusPodvratnik commented on playbooks/3_setup_kvm_host.yaml
> +    - { role: attach_subscription, when:  env.redhat.manage_subscription | upper == 'ATTACH' }
Done.

2023-09-11 07:58 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/all.yaml.template
> +    ip_forward: 0
This make sense ...

2023-09-11 16:22 UTC, jacobemery requested changes
One more comment for you. Suggesting a change to the placement of the conditional for attach_subscription. 

I did see the DCO checks failed. If you could check that out as well.

Otherwise, looks good! Once those are done we can merge.

2023-09-11 16:22 UTC, jacobemery commented on playbooks/3_setup_kvm_host.yaml
> +    - { role: attach_subscription, when:  env.redhat.attach_subscription }
I just realized this role is also used in 5_setup_bastion, so the conditional would have to be changed there as well. 

But, how about instead of putting the conditional at the role-level as we have here and in playbook 5, we put it at the task-level (roles/attach_subscription/tasks/main.yaml) so that way we can remove the conditional from the playbook-level and we don't have the conditional in multiple places. Any future changes would need to be made in only one place, and it makes the playbooks cleaner as well.

2023-09-12 10:37 UTC, AmadeusPodvratnik commented
At the end I was able to sign the commits (accepting changes via web leads commits without signoff).

2023-09-13 20:27 UTC, jacobemery approved these changes
Looks good!

2023-09-13 20:27 UTC, merged