WIP: Enabling disconnected cluster installation
IBM/Ansible-OpenShift-Provisioning pull request #205
Opened 2023-09-21 09:56 UTC by mohammedzee1000

2023-09-27 16:42 UTC, mohammedzee1000 commented on docs/prerequisites.md
> +    Make sure this directory contains a pre-downloaded `oc-mirror` binary in `tar.gz` formal. Currently the supported binary is available for `amd64` on Red Hat Customer portal openshift [downloads](
Todo: mention that currently on oc mirror is fetched from ftp server and all other binaries and the rhcos images are directly downloaded from mirror.openshift.com on mirror host and lpars

2023-09-28 06:13 UTC, mohammedzee1000 commented
It would be nice if i could view the docs shanges in a preview website

2023-09-28 08:47 UTC, mohammedzee1000 commented
@AmadeusPodvratnik @jacobemery open for review, PTAL

2023-09-28 09:51 UTC, AmadeusPodvratnik reviewed
What kind of tests did you execute? Did you test KVM on s390 and x86_64?

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/prerequisites.md
> +    **NOTE**: At this stage, only oc-mirror binary is fetched from here, so it is expected that the lpar for disconnected cluster can atleat reach `mirror.openshift.com` to download the other artifac
Typo .. should be "at least"

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/prerequisites.md
> +    * Make sure you have requisite pull secrets handy as well. You will need 2 pull secrets, one to apply on the cluster and another which will be used for mirroring. The mirroring  pull secret MUST
I would write: Make sure you have required pull secrets handy.

Can you pls rephrase this:
A good way to create this would to create this would be to take this pull secret would be to put the Red Hat pull secret from **Get Info** page and do a podman login with creds having write access.

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/prerequisites.md
> +    Make sure this directory contains a pre-downloaded `oc-mirror` binary in `tar.gz` formal. Currently the supported binary is available for `amd64` on Red Hat Customer portal openshift [downloads](
If you are pointing to architecture than x86_64 is better than amd64 because RH is talking x86_64 on their websites.

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/run-the-playbooks.md
> +* Mirror the platform images using `oc adm release mirror` if legacy mirrorng is enabled.
typo: mirroring (instead of mirrorng)

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
If the user specified the a disconnected install I would say that it makes sense to execute the playbook automatically. In case a cluster should be installed than you have connected or disconnected but in both ways all necessary setup steps should be done automatically. 
Who is setup the mirror host and could the mirror host be the bastion? For NAT it could be the KVM-Host but not for macvtap.

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
@jacobemery What do you think?

2023-09-28 09:51 UTC, AmadeusPodvratnik commented on roles/set_inventory/templates/hosts.j2
> +{{ disconnected.mirroring.host.name | string + ' ansible_host=' + disconnected.mirroring.host.ip | string + ' ansoble_user=' + disconnected.mirroring.host.user | string + ' ansible_become_password='
There is a typo... ansible_user instead of ansoble_user.

2023-09-28 09:52 UTC, AmadeusPodvratnik commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
What about Harbor as an repository?

2023-09-28 10:09 UTC, mohammedzee1000 commented on roles/set_inventory/templates/hosts.j2
> +{{ disconnected.mirroring.host.name | string + ' ansible_host=' + disconnected.mirroring.host.ip | string + ' ansoble_user=' + disconnected.mirroring.host.user | string + ' ansible_become_password='
Fixing typo, pushing shortly

2023-09-28 10:10 UTC, mohammedzee1000 commented on docs/run-the-playbooks.md
> +* Mirror the platform images using `oc adm release mirror` if legacy mirrorng is enabled.
Fixing and pushing shortly

2023-09-28 10:14 UTC, mohammedzee1000 commented on docs/prerequisites.md
> +    Make sure this directory contains a pre-downloaded `oc-mirror` binary in `tar.gz` formal. Currently the supported binary is available for `amd64` on Red Hat Customer portal openshift [downloads](
Fixing and pushing shortly

2023-09-28 10:23 UTC, mohammedzee1000 commented on docs/prerequisites.md
> +    **NOTE**: At this stage, only oc-mirror binary is fetched from here, so it is expected that the lpar for disconnected cluster can atleat reach `mirror.openshift.com` to download the other artifac
Fixing and pushing shortly

2023-09-28 10:44 UTC, mohammedzee1000 commented
I ran tests using one s390x lpar. The same host acts as mirror host and the host for the registry.
1. Ran till `ansible-playbook playbooks/3_setup_kvm_host.yaml`, 
2. Created registry on the host, adding networkmanager dnsmasq entry on the lpar
3. Update pull secrets and cert to inventory
4. Ran the `ansible-playbook playbooks/disconnected_mirror_artifacts.yaml` to mirror to the registry
5. Ran the rest of the playbooks as normal
6. Ran `ansible-playbook playbooks/disconnected_apply_operator_manifests.yaml` at the end.
Also,
1. I also ran reinstall cluster playbook once with disconnected kept enabled and again with disconnected disabled
2. I refreshed lpar, then started with the connected cluster setup and then reinstalled it as disconnected.

2023-09-28 10:51 UTC, mohammedzee1000 commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
A mirror host can be any host. I don't think there is any restriction other than it being linux and being able to access the Red Hat registries, your mirror registry, ftp server, and mirror.openshift.com for the clients.

I think i should reword that and simply say run anytime after the setup playbook

2023-09-28 12:07 UTC, mohammedzee1000 commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
If we want to provide registry setup then we can maybe do it in a separate pr

Like we re doing for ftp server setup

2023-09-28 16:16 UTC, mohammedzee1000 commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
@jacobemery wdyt?

2023-10-06 09:34 UTC, mohammedzee1000 commented
sorry for multiple force pushes, for got to provide signing when rebasing master

2023-10-24 15:28 UTC, AmadeusPodvratnik requested changes
Hi @mohammedzee1000, I got the review from @jacobemery and here are the findings (include some minor stuff from my side).
je: On disconnected, I would follow the same way we did hypershift, a separate 'Run the Playbooks (disconnected) page in the docs, and don't add the disconnected playbooks to the regular 'Run the playbooks' page in docs. It makes It too confusing. All mentions of disconnected in docs/run-the-playbooks.md should be in their own page, like hypershift has. And describe what must be done differently in comparison to a regular install.
ap: So please move all disconnected description to a section above "Run the Playbooks (Hypershift)" and consolidate as for Hypershift. => e.g. no update on site.yaml 
je: And instead of having every disconnected task have to include when: disconnected.enabled, the conditionals should be at the playbook or role-level. He's adding the playbooks to pre-existing-site.yaml, which will mean that all the tasks in that playbook will be printed to the terminal and 'skipped' rather than skipping over the entire playbook or role just once. Either remove the disconnected playbooks from the master playbooks and create a disconnected_site.yaml or put conditionals the import_playbook and/or role calls.
ap: so for example put at least a when condition in playbooks/0_setup.yaml before calling disconnected_check_vars

 Typo: 
 run-the-playbook
 mirror the ocp platform and other nessasary images to the mirror registry => necessary 
 
 all.yaml.template
  Warning: currently, the oc-mirror plugin is officially downloadable to am464 only. => should be amd64.
 platform images will be pushed to {tegistry_url}/{ocp_org}/{ocp_repo}:{ocp_tag => curly bracket is missing

2023-10-26 13:10 UTC, AmadeusPodvratnik approved these changes
Thank you @mohammedzee1000 .. it looks good to me.

2023-10-27 04:25 UTC, mohammedzee1000 commented on docs/run-the-playbooks.md
> +* This playbook can be run at any stage after the **0 Setup** playbook as long as the mirror host is ready. Please just make sure to run this **before** the setup of bastion.
Go indirect input, resolving

2023-10-30 07:47 UTC, merged