Add ipv6 support
IBM/Ansible-OpenShift-Provisioning pull request #209
Opened 2023-10-06 16:27 UTC by AmadeusPodvratnik

These changes are fixing ipv6 support. Introducing new variables for ipv6. ipv6 will be set default (use_ipv6 var is set to True).
Fixing attach_subscription issue.

2023-10-06 16:29 UTC, AmadeusPodvratnik commented
@jacobemery pls have a look. I make ipv6 adr. default but not sure. I think it makes sense to have ipv6 addresses available. Doc will updated accordingly.

2023-10-10 11:39 UTC, AmadeusPodvratnik commented
@smolin-de Can you pls have a quick look on this PR?

2023-10-10 12:16 UTC, smolin-de requested changes

2023-10-10 12:16 UTC, smolin-de commented on playbooks/3_setup_kvm_host.yaml
> +    - { role: attach_subscription, when:  env.redhat.manage_subscription }
In line 47 you are still using the variable "env.redhat.attach_subscription" !

2023-10-10 12:16 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +    - { role: attach_subscription, when: env.redhat.manage_subscription }
In line 47 you are still using "env.redhat.attach_subscription"

2023-10-10 12:16 UTC, smolin-de commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
As I know "enc1" is used on s390x VMs. On arm64 and x86_64 VM's you have a different interface name suffix.
Right now the value in this variable is used on all architectures, which will break Multi-Arch setup with KVM.

2023-10-10 13:44 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +    - { role: attach_subscription, when: env.redhat.manage_subscription }
Fixed

2023-10-10 13:50 UTC, AmadeusPodvratnik commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
Thx for the comment. I did the same like for bastion (there is also enc1 used as a interface name). Is it there the same problem? Within the all.yaml you need to specify the interface and the user can put the correct one. Is this not possible on x86?

2023-10-10 15:17 UTC, smolin-de commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
The issue is if you are using multiple architectures and multiple systems. e.g. on my x86 server the VM interface name is : enp1s0. On a different x86 you may have to use use a different interface name. 
Right now we are not specifying the interface name. It works, because we have only one interface which is used.
I recommend to remove the "**env.cluster.networking.interface** " variable, and focus only required ipv6 changes.

2023-10-10 15:24 UTC, AmadeusPodvratnik commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
Well ... the problem is that if I do not specify the interfaces using ipv5 then the network will not come up properly. I tried to use no ipv4 interface and ipv6 interface and ended up in network issues where VM is not accessible or does not get a ipv6 adr. Therefor I specified the interface.
Is this a day 1 issue, a day 2 issue or both?
Is it necessary to specify different interface names in case that the cluster is spread across multiple LPARs?

2023-10-10 16:17 UTC, smolin-de commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
Day 1 is currently used only on one architecture. So, the issue which I have described above exists when you use Day1 and Day 2 operations in one pipeline.
A potential solution would be to define the VM network interface for each LPAR//server.

2023-10-11 08:32 UTC, smolin-de approved these changes

2023-10-11 08:52 UTC, AmadeusPodvratnik commented on docs/set-variables-group-vars.md
> +**env.cluster.networking.interface** | Name of the networking interface on the bastion from Linux's perspective. Most likely enc1. | enc1
@smolin-de As discussed ... I add the interface to the day2 operation.

2023-10-24 14:04 UTC, merged