Enhancement:  Support for zVM  compute nodes to Hosted Control Plane - vswitch FCP/DASD
IBM/Ansible-OpenShift-Provisioning pull request #227
Opened 2023-12-04 13:34 UTC by veera-damisetti

Enhancement:  Support for zVM  compute nodes to Hosted Control Plane - vswitch FCP/DASD

- Code changes for supporting zVM for Hosted Control Plane
- Supported network type  : vswitch
- Supported disk types: FCP/DASD
- Updated the documentation for the same

2023-12-07 12:01 UTC, AmadeusPodvratnik requested changes

2023-12-07 17:07 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +  compute_node_type:       # zkvm / zvm
Done

2023-12-07 17:07 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +    # zkvm specific parameters
Done

2023-12-08 09:21 UTC, veera-damisetti commented on roles/boot_zvm_nodes_hypershift/tasks/main.yaml
> +      when: "{{ hypershift.agents_parms.zvm_parameters.disk_type == 'dasd' }}"
Done

2023-12-08 09:21 UTC, veera-damisetti commented on roles/setup_for_agents_hypershift/templates/parm-file.parm.j2
> +rd.neednet=1 console=ttysclp0 coreos.live.rootfs_url=http://{{ hypershift.bastion_hypershift }}:8080/rootfs.img ip={{ hypershift.agents_parms.zvm_parameters.nodes[item].osa.ip }}::{{ hypershift.agent
Done

2023-12-08 09:22 UTC, veera-damisetti commented on playbooks/create_hosted_cluster.yaml
> +      when: compute_node_type != 'zvm'
Done

2023-12-15 10:13 UTC, AmadeusPodvratnik approved these changes
Looks good so far. I believe that for lpar support some changes are needed.

2023-12-15 10:13 UTC, merged