Enhancement: Support of OSA for zVM HCP
IBM/Ansible-OpenShift-Provisioning pull request #230
Opened 2024-01-03 05:26 UTC by veera-damisetti

Support of OSA for zVM HCP

- Added changes to support for OSA for zVM HCP
- Changed variable name from osa to interface , to be generic.
- Updated the documentation for the same.

2024-02-12 07:45 UTC, AmadeusPodvratnik requested changes
Pls specify nettype, subchannels and options for network (ZNET).

2024-02-12 07:45 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/all.yaml.template
> +          interface:
Due to the extended scope I would suggest to make a slightly scope. the mentioned id is more or less znet and contains nettype, subchannels and options. Your id variable only contain the subchannels and later you add hardcoded values like qeth or layer2=1. Nettype could be qeth or ctc so I suggest to open this parameter and describe it accordingly.

2024-02-12 07:45 UTC, AmadeusPodvratnik commented on roles/boot_zvm_nodes_hypershift/tasks/main.yaml
> +      shell: oc -n {{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}  patch agent {{ agent_name.stdout.split(' ')[0]  }} -p '{"spec":{"approved":true,"hostname":"comput
As mentioned in the all.yaml section there should not be a hardcoded value for nettype or options.

2024-02-12 07:45 UTC, AmadeusPodvratnik commented on roles/setup_for_agents_hypershift/templates/parm-file.parm.j2
> +rd.neednet=1 console=ttysclp0 coreos.live.rootfs_url=http://{{ hypershift.bastion_hypershift }}:8080/rootfs.img ip={{ hypershift.agents_parms.zvm_parameters.nodes[item].interface.ip }}::{{ hypershift
As mentioned in the all.yaml section there should not be a hardcoded value for nettype or options.

2024-02-16 02:01 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +          interface:
Done

2024-02-16 02:01 UTC, veera-damisetti commented on roles/setup_for_agents_hypershift/templates/parm-file.parm.j2
> +rd.neednet=1 console=ttysclp0 coreos.live.rootfs_url=http://{{ hypershift.bastion_hypershift }}:8080/rootfs.img ip={{ hypershift.agents_parms.zvm_parameters.nodes[item].interface.ip }}::{{ hypershift
Done

2024-02-16 02:01 UTC, veera-damisetti commented on roles/boot_zvm_nodes_hypershift/tasks/main.yaml
> +      shell: oc -n {{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}  patch agent {{ agent_name.stdout.split(' ')[0]  }} -p '{"spec":{"approved":true,"hostname":"comput
Done

2024-02-19 16:09 UTC, AmadeusPodvratnik reviewed
Hi @veera-damisetti Thx for the changes ... only one minor comment about this:
arser.add_argument("--network", type=str, help="Network mode for zvm nodes Supported modes: OSA, vswitch, ROCE, Hyperssockets", required=True)
You are mentioning ROCE and Hypersockets but in the description you have only OSA and vswitches.

2024-02-21 16:00 UTC, veera-damisetti commented
yeah ROCE and Hipersockets should be removed

2024-02-22 08:25 UTC, AmadeusPodvratnik reviewed
Hi @veera-damisetti , pls see my comments ... only minor.

2024-02-22 08:25 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/all.yaml.template
> +            nettype: qeth
Hi @veera-damisetti, I believe that the values for ifname, id and nettype are not common or default (maybe for nettype but not sure here). In addition can you pls document the variables.

2024-02-22 08:25 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/all.yaml.template
> +            subchannels: 0.0.bdf0,0.0.bdf1,0.0.bdf2
see comment above.

2024-02-22 09:18 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +            subchannels: 0.0.bdf0,0.0.bdf1,0.0.bdf2
Done

2024-02-22 09:18 UTC, veera-damisetti commented on inventories/default/group_vars/all.yaml.template
> +            nettype: qeth
Done @AmadeusPodvratnik Updated the documentation

2024-02-22 14:46 UTC, AmadeusPodvratnik reviewed
Pls remove the typo...

2024-02-22 14:46 UTC, AmadeusPodvratnik commented on docs/set-variables-group-vars.md
> +**hypershift.agents_parms.zvm_parameters.nodes[0].interface.nettype** | Network type for zVM guests for network connectivity | qeth
There is a typo ... the vars should be without [0] ...

2024-02-22 15:26 UTC, veera-damisetti commented on docs/set-variables-group-vars.md
> +**hypershift.agents_parms.zvm_parameters.nodes[0].interface.nettype** | Network type for zVM guests for network connectivity | qeth
Done

2024-02-23 07:49 UTC, AmadeusPodvratnik approved these changes
@veera-damisetti Looks good. Thank you.

2024-02-25 10:56 UTC, merged