[WIP] Lpar integration - installation on LPAR as nodes
IBM/Ansible-OpenShift-Provisioning pull request #241
Opened 2024-02-28 14:26 UTC by sandisamp

Create integration of LPAR into playbook - 6_create_nodes

Accordingly tasks and roles have been created.

**Note: This PR is a work in progress. Created for initial reviews and not to make the review process too long. Will update detailed description when PR is ready.**

2024-03-06 13:10 UTC, AmadeusPodvratnik requested changes
Hi @sandisamp , thx for the PR. Following additonal comments:
- There is a description missing what support you are adding (lpar).
- You need to document what your are supporting (Classic vs. DPM, fcp device, etc). 
- You have additional variables defined which needed to be explained and described.
- In your boot_LPAR task I do not see a interface name and you are supporting ipv4 only ... is this correct?

2024-03-20 09:42 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.type != "zvm" and env.bastion.type != "lpar"
@sandisamp 
if available, please add your code to install tessia and all other required packages.

2024-03-27 07:05 UTC, smolin-de commented on roles/install_packages/tasks/main.yaml
> +
This will install tessia_baselib on my  Laptop, on all KVM hosts and on bastion Bastion host.
Why ?

2024-03-27 07:10 UTC, sandisamp commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.type != "zvm" and env.bastion.type != "lpar"
The role to install Tessia is already written  for hyper shift use case. Added it here as well.

2024-03-28 11:39 UTC, AmadeusPodvratnik requested changes
Hi @sandisamp Thx for the lpar. Pls add the description of the lpar to section 3 (Step 3: Set Variables (host_vars)) for the time being. 
In addition pls add a section to the Readme.md (New features) and add your lpar support to it.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> -    - { role: robertdebock.openvpn, tags: openvpn, when: env.setup_openvpn == True and env.z.high_availability == True }
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.installation_type != "zvm" and env.bastion.installation_type != "lpar"
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.installation_type != "zvm" and env.bastion.installation_type != "lpar"
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.installation_type != "zvm" and env.bastion.installation_type != "lpar"
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +      when: env.z.high_availability == True and env.bastion.installation_type != "zvm" and env.bastion.installation_type != "lpar"
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +    - { role: robertdebock.epel, tags: openvpn, when: env.z.high_availability == True and env.bastion.installation_type != "zvm" and env.bastion.installation_type != "lpar"  }
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> -      when: env.setup_openvpn == True and env.z.high_availability == True
The check for env.setup_openvpn should not be removed. Pls add this check.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/tasks/main.yaml
> +          --cmdline 'rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }} coreos.inst.ignition_url=
There is no support for ipv6 (which is available for KVM) is this as designed? If yes, when do you plan to add ipv6 support?

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/tasks/main.yaml
> +          --cmdline 'rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }} coreos.inst.ignition_url=
There is no support for ipv6 (which is available for KVM) is this as designed? If yes, when do you plan to add ipv6 support?

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on inventories/default/host_vars/KVMhostname1-here.yaml.template
> +# Section 7 -live disk info
This new section is for lpar and therefor you should change the description in line 16 to 19.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on inventories/default/host_vars/KVMhostname2-here.yaml.template
> +#    lun_name:
This new section is for lpar and therefor you should change the description in line 16 to 19.

2024-03-28 11:39 UTC, AmadeusPodvratnik commented on inventories/default/host_vars/KVMhostname3-here.yaml.template
> +#    lun_name:
This new section is for lpar and therefor you should change the description in line 16 to 19.

2024-04-07 07:53 UTC, sandisamp commented on inventories/default/host_vars/KVMhostname1-here.yaml.template
> +# Section 7 -live disk info
Updated in lines 16-19

2024-04-07 07:53 UTC, sandisamp commented on roles/boot_LPAR/tasks/main.yaml
> +          --cmdline 'rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }} coreos.inst.ignition_url=
This will be added later. will conduct test and update on this.

2024-04-07 07:54 UTC, sandisamp commented on roles/install_packages/tasks/main.yaml
> +
Yes you are right, I have updated the code for it to only be installed in bastion and lpar based installation only.

2024-04-09 12:42 UTC, AmadeusPodvratnik requested changes
@sandisamp Thank you for the PR. Pls see my comments.

2024-04-09 12:42 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/tasks/main.yaml
> +          --cmdline 'rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }} coreos.inst.ignition_url=
The subnet mast is hardcoded to 255.255.0.0. Better would be to use {{ node.networking.subnetmask }} instead.
In addition there is no ipv6 section. Pls add it to have ipv6 support.

2024-04-09 12:42 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/tasks/main.yaml
> +          --cmdline 'rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }} coreos.inst.ignition_url=
The subnet mast is hardcoded to 255.255.0.0. Better would be to use {{ node.networking.subnetmask }} instead.
In addition there is no ipv6 section. Pls add it to have ipv6 support.

2024-04-09 12:42 UTC, AmadeusPodvratnik commented on playbooks/6_create_nodes.yaml
> +        - control
Do you want to not support the infra nodes than you should mention it in the description.

2024-04-09 12:42 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
> +    - { role: robertdebock.epel, tags: openvpn, when: env.setup_openvpn == True and env.z.high_availability == True  and env.bastion.installation_type != "lpar"  }
Pls use for all cases "env.bastion.installation_type|lower" for installation type because of the control variable "lpar". This would be more failure tolerant and prevent issues in case of typos or camelcase values.

2024-05-21 09:48 UTC, smolin-de commented on roles/dns/tasks/main.yaml
> +  block:
This patch is not required anymore.
We use RHEL 9 as default OS.

2024-05-21 09:48 UTC, smolin-de commented on roles/dns/tasks/initial-resolv.yaml
> +  tags: dns, resolv
This patch is not required anymore.
We use RHEL 9 as default OS.

2024-05-21 09:48 UTC, smolin-de commented on docs/set-variables-host-vars.md
> +**Variable Name** | **Description** | **Example**
Where do I found some information about live disk ?
How do I create such live disk created ?
It is defined as optional, but I guess it is mandatory  when I want to use LPAR install. Correct ?

2024-05-21 09:48 UTC, smolin-de commented on playbooks/0_setup.yaml
> +      when: env.z.lpar1.create == True
Why is this changed ?

2024-05-21 09:48 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
>    roles:
why is" env.setup_openvpn == True" removed from the "when" check ?

2024-05-21 09:48 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +        - control
I do not see an error check ?
What happen if bootstrap install fails ?
Will the creation of compute nodes and control nodes continue ?

2024-05-21 09:48 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +<<<<<<< HEAD
Bad patch !
Merge conflicts are not resolved !!!!!

2024-05-21 09:48 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +>>>>>>> 077c676 (Revert "Deleting entries related to Bootstrap in Haproxy post its del… (#255))
Bad patch !!
Resolve merge conflicts correctly.

2024-05-23 06:18 UTC, sandisamp commented on docs/set-variables-host-vars.md
> +**Variable Name** | **Description** | **Example**
See under important note in same file. It is marked as optional because this file is same for creating regular LPARs as well as LPAR info for booting lpar as a node. The initial use case was just for defining LPAR as a host for KVM nodes.

2024-05-29 13:41 UTC, AmadeusPodvratnik commented on playbooks/6_create_nodes.yaml
> +        - bootstrap
Maybe as am option but not necessary. If you have only lpars than it make sense to use them even for bootstraping. Turning bootstrap node to compute node would make sense. 
We are doing this in several projects. Not sure how simple this to be integrated otherwise another PR makes sense.

2024-06-04 09:10 UTC, sandisamp commented on roles/dns/tasks/initial-resolv.yaml
> +  tags: dns, resolv
I think this patch can remain as it works both with rhel8.x and rhel9.x

2024-06-04 09:14 UTC, sandisamp commented on playbooks/5_setup_bastion.yaml
>    roles:
Added the check

2024-06-04 09:15 UTC, sandisamp commented on playbooks/6_create_nodes.yaml
> +        - control
If there is a boot error the Hmc python script will detect that and will result in FAIL. However configuration errors might need to be debugged and are currently not detectable on boot.

2024-06-04 09:17 UTC, sandisamp commented on playbooks/6_create_nodes.yaml
> +        - bootstrap
I have added support to use bastion and bootstrap to be KVM, with this there is a possibility of not underutilising lpar resources.

For converting bootstrap to worker we can add in a later patch.

2024-06-04 09:30 UTC, smolin-de commented on roles/dns/tasks/initial-resolv.yaml
> +  tags: dns, resolv
RHEL8 is not supported anymore !!!

2024-06-04 10:24 UTC, smolin-de reviewed
I am not able to test the code, but it seems to me that this code does not work if the user defines a non-root user for his bastion host.

2024-06-04 10:24 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +  - { role: install_tessia_baselib, when: env.installation_type|lower == "lpar" }
Bastion user is not necessary a root user. Can a  user, e.g "admin", also install the tessia library ?

2024-06-04 10:24 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +  - { role: install_tessia_baselib, when: env.installation_type|lower == "lpar" }
If not, then you have duplicated code. the lines 85 to 90 should be deleted.

2024-06-04 10:24 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +
In KVM mode we delete / destroy the bootstrap node.
What happen with the bootstrap node in LPAR mode. Is it still running ?

2024-06-04 10:24 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +      when: item in hosts_with_host_vars
This function requires a root user or a user with root access.
Consider to add the line "become: true", in case the user has defined a non root user on his bastion host.

2024-06-04 10:56 UTC, sandisamp commented on playbooks/6_create_nodes.yaml
> +
Yes it will not be teared down or shutdown, as per my previous comment, will add a patch to convert the bootstrap to worker node.

2024-06-04 10:59 UTC, sandisamp commented on playbooks/5_setup_bastion.yaml
> +  - { role: install_tessia_baselib, when: env.installation_type|lower == "lpar" }
Tessie baselib installation is only called once in the playbook from here, other instance is for hypershift. 

So removing this will break the liar installation as no Tessia baselib will be present on the bastion

2024-06-04 11:02 UTC, sandisamp commented on playbooks/6_create_nodes.yaml
> +      when: item in hosts_with_host_vars
Root user is not required to boot lpar nodes, only the python path with the tessia baselib should be accessible. The credentials for HMC will be picked from the configuration. These would suffice to boot.

2024-06-04 11:03 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +  - { role: install_tessia_baselib, when: env.installation_type|lower == "lpar" }
I did not said to remove all lines. The line 91 should be kept. The lines 85 to 90 could be deleted, if you can install the code with a non-root user.

2024-06-04 11:06 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +
When you convert the bootstrap node to a worker node in a later step, what kind of DNS name will use use. Can you give me an example ?

2024-06-04 11:10 UTC, smolin-de commented on playbooks/6_create_nodes.yaml
> +      when: item in hosts_with_host_vars
The boot lpar script will be copied to: "/root/ansible_workdir/boot_lpar.py". This is a hardcoded value. Only root or sudo users have a access to it. Did you test your code with an not-root bastion user ?

2024-06-04 11:20 UTC, sandisamp commented on playbooks/6_create_nodes.yaml
> +
This node should resolve to the bootstrap hostname entry in the dns, and once completed the haproxy would need to be updated.

2024-06-05 06:53 UTC, AmadeusPodvratnik approved these changes

2024-06-05 06:53 UTC, AmadeusPodvratnik commented on playbooks/6_create_nodes.yaml
> +        - control
My view on this is, that we can live with that because we have other places doing more or less the same. So for the time being it is ok. We need to convert bootstrap to worker node like we do it in other automation tools.

2024-06-05 06:53 UTC, AmadeusPodvratnik commented on playbooks/6_create_nodes.yaml
> +
This is ok for me.

2024-06-05 06:53 UTC, merged

2024-06-19 10:03 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: