fix: DNS issues
IBM/Ansible-OpenShift-Provisioning pull request #253
Opened 2024-03-21 09:07 UTC by smolin-de

This patch fixes #252 'setup bastion fails for 3 node cluster'

2024-03-21 13:07 UTC, AmadeusPodvratnik requested changes
Hi @smolin-de thx for the fix. Pls see my comments.

2024-03-21 13:07 UTC, AmadeusPodvratnik commented on roles/dns/tasks/main.yaml
> +  when: env.cluster.nodes.compute.hostname is defined
I would suggest to change to 
 when: env.cluster.nodes.compute.hostname[0] is defined and env.cluster.nodes.compute.hostname[0] != None 
 because our template has a defined compute node structure. We can't expect Ansible knowledge from user side so it is better to be more tolerant. 
 The same for the check_dns role.

2024-03-21 14:28 UTC, smolin-de commented on roles/dns/tasks/main.yaml
> +  when: env.cluster.nodes.compute.hostname is defined
It is sufficient to check only for "env.cluster.nodes.compute.hostname[0] is defined".

I used the same check as we use already for infra nodes. "when: env.cluster.nodes.infra.hostname is defined" is used multiple time.

But, why we should allow the user to create empty variables ?
We should change our template and not allow empty variables.

2024-03-21 14:38 UTC, AmadeusPodvratnik commented on roles/dns/tasks/main.yaml
> +  when: env.cluster.nodes.compute.hostname is defined
Ok ... understood ... so how do you want to change the template? In addition we need to describe what to do for what kind of cluster, correct?

2024-03-21 15:01 UTC, AmadeusPodvratnik commented on roles/dns/tasks/main.yaml
> +  when: env.cluster.nodes.compute.hostname is defined
If template must be changed or the user need to do some specific steps than we need to document it. I personally would suggest to make the when clauses more error tolerant but can go with both ways ... document it or change the when clause.

2024-03-22 12:19 UTC, smolin-de commented
@AmadeusPodvratnik 
I updated this patch. 
I will create additional patches for other check improvements.

2024-03-22 16:12 UTC, AmadeusPodvratnik requested changes
Thank you @smolin-de , I identified another line to be changed.

2024-03-22 16:12 UTC, AmadeusPodvratnik commented on roles/dns/tasks/main.yaml
> +  when: env.cluster.nodes.compute.hostname is defined and env.cluster.nodes.compute.hostname[0] is defined and env.cluster.nodes.compute.hostname[0] != None
Line 62 contains 
when: env.cluster.nodes.compute.hostname is defined
but should have the same when statement.

2024-03-25 07:33 UTC, AmadeusPodvratnik approved these changes
@smolin-de Thank you.. looks good.

2024-03-25 07:33 UTC, merged

2024-06-19 10:04 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: