ABI SNO On KVM
IBM/Ansible-OpenShift-Provisioning pull request #263
Opened 2024-03-29 04:28 UTC by isumitsolanki

Addes support for Agent Based Installer SNO (Single Node) on KVM

2024-04-02 12:04 UTC, smolin-de commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/{{ env.cluster.networking.metadata_name }}.s390x-rootfs.img" \
You are using hardcoded architecture for kernel and inirrd ?
Why ?
AOP can be used to install a cluster on a x86 , s390x  or ARM host. Why you are limiting ABI to only s390x ?

2024-04-02 12:58 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/{{ env.cluster.networking.metadata_name }}.s390x-rootfs.img" \
Hi @smolin-de , Agree with you it was just naming clacher I will remove s390x and it will be generic name.

2024-04-02 15:08 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/{{ env.cluster.networking.metadata_name }}.s390x-rootfs.img" \
Hi @smolin-de , Please have a glance here f44adc6f5aa5d9c74af2946714ea76ff4b4f68c9

2024-04-03 04:55 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion and control_node_count | int > 1}
Do not change this line.
This will break the existing SNO install using bootstrap node.
Your sno_haproxy role will overwrite the happroxy setup anyhow, if it is used.
Or you add this change:
```suggestion
    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion and abi.flag is not defined and abi.flag }
```

2024-04-03 04:58 UTC, smolin-de commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/{{ env.cluster.networking.metadata_name }}.s390x-rootfs.img" \
Please use the variables "rhcos_download_url", rhcos_live_kernel", "rhcos_live_initrd" and "rhcos_live_rootfs". These are already defined and used in other roles which create a KVM guest.
e,g,
--extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/bin/{{ rhcos_live_rootfs }}" \

2024-04-03 07:40 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "coreos.live.rootfs_url=http://{{ env.bastion.networking.ip }}:8080/{{ env.cluster.networking.metadata_name }}.s390x-rootfs.img" \
I think I can't use those variable @smolin-de , As it is the main differences PXE boot. We must have to use boot file created by PXE boot as we are feeding here agent-config and install-config. After consuming agent-config and install config openshift installer is giving us PXE boot files to boot the KVM Guest. We must have to use that.

2024-04-03 07:41 UTC, isumitsolanki commented on playbooks/5_setup_bastion.yaml
> +    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion and control_node_count | int > 1}
Ok I will do the changes and test it and commit once it work as expected. Thank you

2024-04-04 06:09 UTC, isumitsolanki commented on playbooks/5_setup_bastion.yaml
> +    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion and control_node_count | int > 1}
Removed check for haroxy as sno_haproxy role will overrite the outcomes. Please have a look at this dbdc74e3b8e8d0c80c52c5843e5a9720d2c2444c

2024-04-05 07:13 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +    - { role: sno_haproxy, when: env.bastion.options.loadbalancer.on_bastion and control_node_count | int == 1 }
```suggestion
    - { role: sno_haproxy, when: env.bastion.options.loadbalancer.on_bastion and (control_node_count | int == 1) and abi.flag is defined and abi.flag  }
```

2024-04-05 07:13 UTC, smolin-de commented on playbooks/5_setup_bastion.yaml
> +    - { role: get_ocp, when: abi.flag is defined and abi.flag != True }
When abi.flag is not defined, then the role "get_ocp" is not executed !
This will break current setup.

2024-04-10 07:12 UTC, isumitsolanki commented on playbooks/5_setup_bastion.yaml
> +    - { role: get_ocp, when: abi.flag is defined and abi.flag != True }
Hi @smolin-de I believe that all.yaml will be already present there and I have given default value as False so in other use case we will get the value for this variable as well

2024-04-17 12:15 UTC, AmadeusPodvratnik requested changes
Hi @isumitsolanki I realize that the closed PR contained some comments from my side. I add them to this PR. Pls close the conversation if done or comment them. Thx.

2024-04-17 12:15 UTC, AmadeusPodvratnik commented on playbooks/5_setup_bastion.yaml
>      - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
Do you need both roles (haproxy and sno_haproxy) in case of sno? If haproxy and sno_haproxy are exclusively than you need to add the flag check otherwise you can just close this conversation.

2024-04-18 08:56 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.control.disk_size }} \
Hi @AmadeusPodvratnik , I have tried `cache=none,io=native ` in disk pool. It is working fine as expect done the changes and tested in local environment. Please have a glance on it 3267f10b7634c10a4963c9a9db9ca847fd7ac004

2024-04-18 08:57 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "{{ _vm_console }}" \
I have tried this with above changes it is working fine after doing code changes. 3267f10b7634c10a4963c9a9db9ca847fd7ac004

2024-04-18 09:58 UTC, isumitsolanki commented on playbooks/5_setup_bastion.yaml
>      - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
Yes @AmadeusPodvratnik , When I will be doing HA (3+2) using ABI during that automation I will be needed this HA proxy and sno_haproxy will get skipped. So I am keeping that in my mind and I spoke to @smolin-de as well he has suggested due to my check for skip HAProxy it may failed in error in existing SNO installation using bootstrap.

2024-04-18 11:31 UTC, isumitsolanki commented on docs/run-the-playbooks-for-abi.md
> +* As of now we are supporting only macvtap for Agent based installation (ABI) for KVM compute nodes.
This note has been accommodate in document a10fdd955a8e01b811e659e66217a66b2750aeaf

2024-04-18 11:32 UTC, isumitsolanki commented on roles/prepare_configs/templates/install-config.yaml.j2
> +  - cidr: 172.23.0.0/16
I have done the changes for it and tested locally by bringing up SNO on KVM it is working fine.

2024-04-18 11:36 UTC, isumitsolanki commented
> Hi @isumitsolanki I realize that the closed PR contained some comments from my side. I add them to this PR. Pls close the conversation if done or comment them. Thx.

Yeah @AmadeusPodvratnik , I have checked raise concerns and suggestion and done the changes respectively and done the testing as well. please have look again.

2024-04-23 13:22 UTC, AmadeusPodvratnik approved these changes
Hi @isumitsolanki Thx for the PR. Looks good so far.

2024-04-23 13:22 UTC, merged

2024-06-19 10:04 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: