Ansible-OpenShift-Provisioning To ABI SNO On KVM
IBM/Ansible-OpenShift-Provisioning pull request #264
Opened 2024-04-01 04:35 UTC by isumitsolanki

Provided support to ABI (Agent Based Installation) SNO (Single Node Cluster) On KVM

2024-04-02 07:52 UTC, smolin-de commented on inventories/default/group_vars/all.yaml.template
> +  ocp_installer_url: 'https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/'
Why you are not using the OCP multi-playload link ?

2024-04-02 09:07 UTC, isumitsolanki commented on inventories/default/group_vars/all.yaml.template
> +  ocp_installer_url: 'https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/'
As of now we are just supporting s390x arch in case of ABI so that using above url.

2024-04-05 11:21 UTC, AmadeusPodvratnik requested changes
Thx @isumitsolanki for the PR. Pls see my comments.

2024-04-05 11:21 UTC, AmadeusPodvratnik commented on roles/prepare_configs/templates/install-config.yaml.j2
> +  - cidr: 172.23.0.0/16
Pls use env.install_config.service_network instead of hard coded value.

2024-04-05 11:21 UTC, AmadeusPodvratnik commented on docs/run-the-playbooks-for-abi.md
> +* As of now we are supporting only macvtap for Agent based installation (ABI) for KVM compute nodes.
Pls document that only single KVM cluster is supported.

2024-04-05 11:26 UTC, AmadeusPodvratnik requested changes

2024-04-05 11:26 UTC, AmadeusPodvratnik commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "rd.neednet=1 nameserver={{ env.cluster.networking.nameserver1 }}" \
As of @smolin-de PR disabling memballon pls add:
 --memballoon none \
 --graphics none \

2024-04-05 11:36 UTC, AmadeusPodvratnik requested changes

2024-04-05 11:36 UTC, AmadeusPodvratnik commented on roles/boot_abi_agents/tasks/main.yml
> +    --disk pool={{ env.cluster.networking.metadata_name }}-vdisk,size={{ env.cluster.nodes.control.disk_size }} \
As of the PR from @smolin-de pls add 
,cache=none,io=native
to the disk pool.

2024-04-12 06:19 UTC, isumitsolanki commented
Duplicate PR hence closing one

2024-04-12 06:19 UTC, closed without merging