Added Support For HA (3+2) Using ABI On KVM
IBM/Ansible-OpenShift-Provisioning pull request #277
Opened 2024-05-03 14:04 UTC by isumitsolanki

2024-05-06 07:03 UTC, AmadeusPodvratnik requested changes
Hi @isumitsolanki Thx for the review. Pls see my comments regarding kargs.

2024-05-07 09:34 UTC, isumitsolanki commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "rd.neednet=1 nameserver={{ env.cluster.networking.nameserver1 }}" \
Hi @AmadeusPodvratnik , without providing all those parameters mentioned above. It's working fine for me. Can you please suggest me what should I do. ? Shall I provide above parameters mentioned by you.??

2024-05-07 12:50 UTC, v78singh commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "rd.neednet=1 nameserver={{ env.cluster.networking.nameserver1 }}" \
@AmadeusPodvratnik for Agent based installer there is no ipxe script generated and we just get the images directly as artifacts. We did the test with the minimal config (kargs )needed to boot the VM successfully. This PR utilizes only those params.

2024-05-08 13:14 UTC, AmadeusPodvratnik commented on roles/boot_abi_agents/tasks/main.yml
> +    --extra-args "rd.neednet=1 nameserver={{ env.cluster.networking.nameserver1 }}" \
Ok .. so than for the time being use exactly those kargs you used for testing. Assisted Installer is using the kargs provided by the assisted services (generic.prm form ISO). 
For 4.17 I will provide the generic.prm file for agent-based installer so than it might be clearer what RH suggested to be used.

2024-05-08 13:15 UTC, AmadeusPodvratnik approved these changes
@isumitsolanki Thank you, will approve.

2024-05-08 13:15 UTC, merged

2024-06-19 10:04 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: