Added the Role for Reverse DNS when IPs of nodes falls under differen…
IBM/Ansible-OpenShift-Provisioning pull request #284
Opened 2024-06-07 09:09 UTC by k-shiva-sai

When the Bastion node IPs and OCP node IPs falls differnet subnet zones say 172.23.233.156 be bastion and 172.23.230.64 be master then while setting the rever DNS zone it assume nodes ips also falls under same zone and  adds the ip to bastion zone due to which nslookup fails. 
To allow this I have added a role multisubnet_reverse_dns which resolves like this.
```
$ORIGIN 230.23.172.in-addr.arpa.
64 IN PTR master0.ocpz.lnxne.boe.
65 IN PTR master1.ocpz.lnxne.boe.
66 IN PTR master2.ocpz.lnxne.boe.
54 IN PTR worker0.ocpz.lnxne.boe.
68 IN PTR worker1.ocpz.lnxne.boe.
72 IN PTR bootstrap.ocpz.lnxne.boe.
$ORIGIN 233.23.172.in-addr.arpa.
156 IN PTR bastion.ocpz.lnxne.boe.
156 IN PTR api.ocpz.lnxne.boe.
156 IN PTR api-int.ocpz.lnxne.boe.
```
and the named conf changes like this
```
zone "23.172.in-addr.arpa" IN {
     type master;
     file "/var/named/ocpz.rev";
     allow-update { any; };
     allow-query { any; };
};

```

2024-06-10 15:45 UTC, AmadeusPodvratnik requested changes
Hi @k-shiva-sai Thank you for the PR. Pls check my comments.

2024-06-10 15:45 UTC, AmadeusPodvratnik commented on roles/multisubnet_reverse_dns/tasks/main.yml
> +    path: /root/ansible_workdir/
This might fail if user is not root user. For temporary files use e.g. /tmp folder where usually everyone has access to.

2024-06-10 15:45 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/all.yaml.template
> +  multi_subnet: False // Plese set this Option True for setting up the Reverse dns when IPs of nodes falls in differnet subnets
Pls document this new parameter in the docs section, too.

2024-06-10 15:45 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/templates/boot_lpar.py
> +if lpar_name[0:3] in ["m13", "m42"]:
This is hardcoded and might lead to errors if something changed. Pls use wars for that if needed.

2024-06-11 06:51 UTC, sandisamp commented on roles/boot_LPAR/templates/boot_lpar.py
> +if lpar_name[0:3] in ["m13", "m42"]:
This should be taken as a variable in the host vars

2024-06-19 06:25 UTC, closed without merging