Livedisk with FCP changes
IBM/Ansible-OpenShift-Provisioning pull request #286
Opened 2024-06-11 16:29 UTC by k-shiva-sai

Enables to use the FCP live disk to boot the nodes.

2024-06-12 06:51 UTC, sandisamp requested changes

2024-06-12 06:51 UTC, sandisamp commented on roles/boot_LPAR/tasks/main.yaml
> +          --livediskwwpn {{ live_disk_wwpn }} \
This is duplicate code

2024-06-12 07:10 UTC, sandisamp approved these changes

2024-06-12 11:49 UTC, AmadeusPodvratnik requested changes
Hi @k-shiva-sai Thank you for the PR. Pls see my comments.

2024-06-12 11:49 UTC, AmadeusPodvratnik commented on docs/set-variables-host-vars.md
> +**lpar.livedisk.livedisktype** | <b>(Optional)</b> Storage type. DASD and SCSI are tested types as of now. | dasd
Now you are supporting DASD and FCP devices (Do you really mean SCSI and not FCP?) and the question is what exactly need to be defined. It would be good to be precise. If no lun or wwpn is defined than the devicenr is taken as DASD with the lun and wwpn it's for FCP devices.

2024-06-12 11:49 UTC, AmadeusPodvratnik commented on roles/boot_LPAR/templates/boot_lpar.py
> +if args.livedisklun!="na" and args.livediskwwpn!="na":
There is no further logic check. If FCP is being specified but no lun or wwpn given or if DASD specified and lun and wwpn given. It would be good to have some checking for logic errors.

2024-06-12 12:47 UTC, k-shiva-sai commented on roles/boot_LPAR/templates/boot_lpar.py
> +if args.livedisklun!="na" and args.livediskwwpn!="na":
Thanks Amadeus for the comment.
I will work on this and raise the commit.

2024-06-12 18:13 UTC, k-shiva-sai commented on docs/set-variables-host-vars.md
> +**lpar.livedisk.livedisktype** | <b>(Optional)</b> Storage type. DASD and SCSI are tested types as of now. | dasd
Node boot Works only when the livedisktype is scsi it is throwing errors when it is fcp.

2024-06-14 12:05 UTC, AmadeusPodvratnik approved these changes
Thx @k-shiva-sai Looks good so far.

2024-06-14 12:06 UTC, merged

2024-06-19 10:03 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: