Enhancement: Moving HCP variables to a separate var file
IBM/Ansible-OpenShift-Provisioning pull request #300
Opened 2024-07-09 13:33 UTC by veera-damisetti

Enhancement: Moving HCP variables to a separate var file 

- Introduced a new all.yaml.hcp.template for hcp vars
- Removed all hcp related vars from all.yaml
- Restructured HCP vars to make it more user friendly
- Added support for DASD disk for KVM guests
- Updated docs

2024-07-11 13:33 UTC, AmadeusPodvratnik requested changes
Hi @veera-damisetti Thx for the PR. Pls see my comments and in addition could you pls provide a README update in the what's new section. Thx.

2024-07-11 13:33 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/hcp.yaml.template
> +  bastion_params:
Would it make sense to have a common bastion hosting all necessary stuff (dns, haproxy, etc).
Due to the split it might be useful not to have to many variable dubs.

2024-07-11 13:54 UTC, veera-damisetti commented on roles/install_tessia_baselib/tasks/main.yaml
> +  loop: "{{ hcp.pkgs.zvm }}"
Sure @AmadeusPodvratnik
make sense
Updated

2024-07-11 13:56 UTC, veera-damisetti commented on inventories/default/group_vars/hcp.yaml.template
> +  bastion_params:
you mean common bastion for Hosted Cluster and Management OCP cluster ?

2024-07-12 14:06 UTC, AmadeusPodvratnik commented on inventories/default/group_vars/hcp.yaml.template
> +  bastion_params:
Ok ... as discussed via Slack for the time being hcp is having it's own bastion.

2024-07-12 14:34 UTC, AmadeusPodvratnik commented on roles/install_tessia_baselib/tasks/main.yaml
> +  loop: "{{ hcp.pkgs.zvm }}"
As discussed via Slack we need here a followup to not duplicate variables for every component. So we need to have a follow-up here. For the time being HCP is more or less independent from a regular OCP installation but is still part of the project and should fit into.

2024-07-12 14:35 UTC, AmadeusPodvratnik approved these changes
As discussed via Slack go for now because HCP is some sort of independent.

2024-07-12 14:35 UTC, merged

2024-07-12 14:36 UTC, veera-damisetti commented
Thanks @AmadeusPodvratnik

2024-11-06 11:27 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: