OpenShift Client issue has been resolved along with DNS issue
IBM/Ansible-OpenShift-Provisioning pull request #367
Opened 2024-12-13 13:50 UTC by isumitsolanki

This is pull request is having fix for below two issue  (ABI Disconnected)
[OpenShift Client in not getting download from file_server ](https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/366)

[ABI: On fresh z/VM bastion ABI playbook is not installing tessia base lib](https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/365)

2024-12-18 09:53 UTC, AmadeusPodvratnik requested changes
Hi @isumitsolanki Thank you for the PR, pls see my comment.

2024-12-18 09:53 UTC, AmadeusPodvratnik commented on roles/offline_artifacts/tasks/main.yaml
> +        # - "{{ env.file_server.protocol }}://{{ env.file_server.user + ':' + env.file_server.pass + '@' if env.file_server.protocol == 'ftp' else '' }}{{ env.file_server.ip }}{{ ':' + env.file_serve
Hi @isumitsolanki, you commented the code. Is this your intention? 
If the code is not being used anymore, than delete it because this keeps the code clean. Thx.

2024-12-18 13:46 UTC, isumitsolanki commented on roles/offline_artifacts/tasks/main.yaml
> +        # - "{{ env.file_server.protocol }}://{{ env.file_server.user + ':' + env.file_server.pass + '@' if env.file_server.protocol == 'ftp' else '' }}{{ env.file_server.ip }}{{ ':' + env.file_serve
Hi @AmadeusPodvratnik , I just want to unblock solution team for that I have commented but this we have to discuss and then we will draw a solution. I  think whatever this written here the correct logic but solution team don't have access to keep oc client in the mentioned directory over filer-server. so in that case for as now i enabled to reach from internet as well.

2024-12-18 13:50 UTC, AmadeusPodvratnik commented on roles/offline_artifacts/tasks/main.yaml
> +        # - "{{ env.file_server.protocol }}://{{ env.file_server.user + ':' + env.file_server.pass + '@' if env.file_server.protocol == 'ftp' else '' }}{{ env.file_server.ip }}{{ ':' + env.file_serve
This is understood but why you can't remove the lines and if needed bring it back?

2024-12-18 13:59 UTC, isumitsolanki commented on roles/offline_artifacts/tasks/main.yaml
> +        # - "{{ env.file_server.protocol }}://{{ env.file_server.user + ':' + env.file_server.pass + '@' if env.file_server.protocol == 'ftp' else '' }}{{ env.file_server.ip }}{{ ':' + env.file_serve
ok sure @AmadeusPodvratnik , I will do the same

2024-12-18 14:06 UTC, AmadeusPodvratnik approved these changes
@isumitsolanki Thank you. /lgtm

2024-12-18 14:06 UTC, merged

2025-05-15 12:35 UTC, AmadeusPodvratnik commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: