Easier OCP versioning
IBM/Ansible-OpenShift-Provisioning pull request #78
Opened 2023-01-24 02:02 UTC by jacobemery

Previous method for selecting the OpenShift version in all.yaml was unnecessarily cumbersome, requiring copying 5 different mirror links to variables.

This make it so you just set one variable env.openshift.version to the desired version (i.e. 4.12) and the automation does the rest.

Signed-off-by: Jacob Emery <jacob.emery@ibm.com>

2023-01-24 02:03 UTC, jacobemery commented
@smolin-de Could you review this for me?

2023-01-24 02:22 UTC, jacobemery reviewed
References to architecture and references to the major version in the mirror links have also been turned into variables for future-proofing.

2023-01-24 05:19 UTC, smolin-de commented
In general I like this change.
You are using just "major.minor" version (4.12) and getting always the the latest fix version. So you always install the latest available version.
Was this requested from someone ?
I prefer to specify the entire version, e.g. 4.12.0. I can always updated to the latest version later, if and when I like.
This give me more flexibility.

2023-01-25 07:49 UTC, jacobemery commented
@smolin-de when merging, could you change this PRs title to "feat: improve OCP versioning #78" to match the semantic release naming conventions?

2023-01-25 08:05 UTC, smolin-de requested changes

2023-01-25 08:05 UTC, smolin-de commented on roles/get_ocp/tasks/main.yaml
> +- name: Delete bin and ignition folders for idempotency.
In future,  we should only delete files which could cause problems.

2023-01-25 08:47 UTC, jacobemery commented on roles/get_ocp/tasks/main.yaml
> +- name: Delete bin and ignition folders for idempotency.
https://github.com/IBM/Ansible-OpenShift-Provisioning/pull/78/commits/cde53950ce71a4d0dfec9a530812ecf460dab5a1

2023-01-26 15:36 UTC, smolin-de approved these changes

2023-01-26 15:55 UTC, merged

2023-02-17 16:24 UTC, jacobemery commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/Ansible-OpenShift-Provisioning/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: